name: KDotH

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    name: Test ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Just
      uses: extractions/setup-just@v3

    - name: Update Dependencies
      run: just --no-deps ci-deps

    - name: Update Submodules
      run: just --no-deps sync

    - name: Configure
      run: just --no-deps gen debug

    - name: Build
      run: just --no-deps build debug

    - name: Test
      run: just --no-deps test debug
